### ISSUE TITLE
Fight Shadow Affinity bosses if copied outside Shadow Rifts

### ISSUE THREAD

**Issue by plasticmacaroni** [C2Talon/c2t_hccs#14]
if (have_effect($effect[shadow affinity]) == 0 && !contains_text(my_location(), "Shadow Rift"))

Added the second part -- should make sure when fighting a shadow affinity enemy that if it's outside a shadow rift, you don't need to abort because you don't have the shadow affinity

**Comment by plasticmacaroni** [comment]
https://github.com/C2Talon/c2t_hccs/pull/15/commits/71c6631295ff46683bd565280b050f27dcd657f7

**Comment by plasticmacaroni** [comment]
Oops, needed to reverse the sign after testing

**Comment by C2Talon** [comment]
There should be no fighting of shadow rift monsters outside the shadow rift, and shadow rift bosses cannot be copied. So this is just confusing. Is there a log of that happening?

**Comment by plasticmacaroni** [comment]
Maybe it's a Mafia error then? The logs would be wrong then, unless backing up shadow rift monsters is possible. Here's an example log, but I can provide more. I had to manually kill the shadow rift enemy to keep the script going. If you'd prefer not to update for this edge case, that's fine! 

[65] The Neverending Party
Preference lastEncounter changed from burnout to party girl
Encounter: party girl
Round 0: player wins initiative!
Round 1: Your toy train moves ahead to the Viewing Platform. As your train passes the viewing platform, the crowd shouts and cheers inspiring you!
Preference trainsetPosition changed from 27 to 28
Round 1: You gain 207 Muscleboundness
Round 1: You gain 137 Wizardliness
Round 1: You gain 317 Chutzpah
> c2t_bb macro: scrollwhendone;pickpocket;if hasskill 7381;skill 7381;endif;twiddle;
Round 1: player executes a macro!
Round 1: player tries to steal an item!
You acquire an item: very small red dress
Round 2: Wusevelt lights a sparkler and stabs your foe with it for 20 damage. Some of the sparks land right on your brain! Whooo!
Round 2: You gain 20 Mojo Points
Round 2: You lose 128 hit points
Round 2: player casts BACK-UP TO YOUR LAST ENEMY!
Round 3: your opponent becomes a shadow guy!
Preference _backUpUses changed from 5 to 6
Preference choiceAdventureScript changed from c2t_hccs_choices.ash to 
Preference betweenBattleScript changed from c2t_hccs_preAdv.ash to 
Preference afterAdventureScript changed from c2t_hccs_postAdv.ash to 
Preference recoveryScript changed from c2t_hccs_recovery.ash to 
Preference hpAutoRecoveryItems changed from cannelloni cocoon;tongue of the walrus;disco nap to scroll of drastic healing;cannelloni cocoon;relaxing hot tub;tongue of the walrus;lasagna bandages
Preference hpAutoRecovery changed from 0.9 to -0.05
Preference hpAutoRecoveryTarget changed from 0.95 to 0.0
Preference currentMood changed from hccs-mox to apathetic
> c2t_hccs took 0 minutes 2.291 seconds to execute.
Round 3: player casts SAUCEGEYSER!
Round 4: shadow guy takes 484 damage.
Round 4: Wusevelt shoots your foe with a patriotic firework, causing 31 damage. "Ooh!" you say, dutifully. "Ahh!" "Ouch!" your opponent adds.
Round 4: You gain 31 Mojo Points
Round 4: player wins the fight!
After Battle: I bet you didn't know that the shadow guy keeps itself hydrated by storing emergency water in its butt, like a camel.
You acquire an effect: Ultrahydrated (5)
You acquire an item: shadow bread
After Battle: Wusevelt grins at you, which is weird because of the beak? (+10 Stats)
After Battle: You gain 58 Fortitude
You gain a Muscle point!
After Battle: You gain 40 Magicalness
After Battle: You gain 168 Chutzpah
You gain a Moxie point!
After Battle: You gain 1 Magicalness
Preference garbageShirtCharge changed from 32 to 31
Preference encountersUntilNEPChoice changed from 2 to 1
Preference _boomBoxFights changed from 1 to 2
Preference _concoctionDatabaseRefreshes changed from 125 to 126
Preference _concoctionDatabaseRefreshes changed from 126 to 127
Preference afterAdventureScript changed from  to c2t_hccs_postAdv.ash
Preference betweenBattleScript changed from  to c2t_hccs_preAdv.ash
Preference choiceAdventureScript changed from  to c2t_hccs_choices.ash
Preference hpAutoRecovery changed from -0.05 to 0.9
Preference hpAutoRecoveryItems changed from scroll of drastic healing;cannelloni cocoon;relaxing hot tub;tongue of the walrus;lasagna bandages to cannelloni cocoon;tongue of the walrus;disco nap
Preference hpAutoRecoveryTarget changed from 0.0 to 0.95
Preference recoveryScript changed from  to c2t_hccs_recovery.ash
> Checking test 11: Coil Wire
> Checking test 4: Feed Conspirators
> not using trash love potion
> Info: don't have the skill "Stevedave's Shanty of Superiority" to get the "Stevedave's Shanty of Superiority" effect
Preference currentMood changed from apathetic to hccs-mox
Preference nextAdventure changed from The Neverending Party to None
> Running backup camera and Neverending Party fights
Preference nextAdventure changed from None to The Neverending Party
Maximizer: -tie,mainstat,exp,equip ¶10058,100 bonus ¶10929,equip ¶9699

**Comment by C2Talon** [comment]
The script should only be backing up into sausage goblins. There is no provision to backup into any other monster, and especially not into non-free monsters like the shadow rift ones. If you could provide the log from the start of the run up until that point, as well as a link to the IotMs you have (snapshot or greenbox), it'll help me try to figure out what went wrong.

Edit2: if don't want to send those publicly, you can PM me them on github if PMs exist here. Or to `c2t` on discord, assuming you're on the Ascension Speed Society server

Edit: as a bypass for now, you could disable using the backup camera via the relay script so its uses are not wasted on non-free monsters, at least until I get to the bottom of what's going on

**Comment by plasticmacaroni** [comment]
Sure thing! If you think this is outside the scope of what you'd like to do, I totally understand, and you can close this. I don't think this is doxxing myself, here's my log from the last run until it got stuck. 

[11-30-2024.txt](https://github.com/user-attachments/files/17964769/11-30-2024.txt)

Edit: greenboxes sent over Discord PM

**Comment by C2Talon** [comment]
So yeah, the required IotMs are required because the design and script assumes the person has them. And I just have no idea how the script might behave with someone who doesn't have one or more of of the requirements.

I kind of guessed you might not have Kramco if you weren't getting a sausage goblin from back-ups. I've been meaning to move Kramco to a not strictly required IotM since the bat wings came out with its strong and easier MP restore. But there is more than just MP restore that Kramco does, like the wandering monster it provides being the target of all copy abilities used, that it's not so easy to make optional without many other considerations.

As for the other things you're missing, they could technically be optional one day easier than Kramco, but still difficult because they would each require different routing considerations, and likely multiple routes depending on what combination of IotMs and other tools a person has.
